# safelist
branches:
  only:
    - dev

language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

script:
  - make cov_test