# safelist
# branches:
#   only:
#     - dev

language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pokepare.settings.travis"

services:
  - postgresql
  - elasticsearch

addons:
  postgresql: "9.4"

before_script:
  - sleep 15

script:
  - python manage.py add_images -dir /home/travis/build/Synkied/pokepare/mock_data/ -import_type all
  - make cov_test