version: '3'

services:

  traefik:
    container_name: traefik
    restart: always
    image: traefik
    volumes:
      - ./traefik/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
      - '443:443'
    networks:
      - pokepare_net

  pokepare_nginx:
    container_name: pokepare_nginx
    restart: always
    image: nginx
    depends_on:
      - pokepare_py
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - '8060:80'
    networks:
      - pokepare_net
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=pokepare_nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pokepare.com,www.pokepare.com'

  pokepare_py:
    container_name: pokepare_py
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    depends_on:
      - pokepare_db
      - elasticsearch
    links:
      - pokepare_db:database
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./:/usr/src/app
    networks:
      - pokepare_net

  pokepare_db:
    container_name: pokepare_db
    restart: always
    image: postgres
    networks:
      - pokepare_net

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - pokepare_net

networks:
  pokepare_net:
    driver: bridge