version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    environment:
      - DEFAULT_HOST=pokepare_py.local
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - pokepare_net

  pokepare_nginx:
    container_name: pokepare_nginx
    restart: always
    image: nginx
    depends_on:
      - pokepare_py
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    environment:
      - VIRTUAL_HOST=pokepare_nginx.local
      - VIRTUAL_PORT=8060
    networks:
      - pokepare_net

  pokepare_py:
    container_name: pokepare_py
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    depends_on:
      - pokepare_db
    links:
      - pokepare_db:database
    environment:
      - PYTHONUNBUFFERED=0
      - VIRTUAL_HOST=pokepare_py.local
      - VIRTUAL_PORT=8060
    volumes:
      - ./:/usr/src/app
    networks:
      - pokepare_net

  pokepare_db:
    container_name: pokepare_db
    restart: always
    image: postgres
    networks:
      - pokepare_net

networks:
  pokepare_net:
    driver: bridge